language: php
 
php:
  - 5.4
  - 5.5
  - 5.6	 
  - 7.0
  - hhvm

services:
  - mysql
  
before_script:
  - mysql -e 'create database jaeger_settings;'
  - mysql -u root jaeger_settings < data/settings_table.sql
  - composer self-update
  - composer install --prefer-source --no-interaction
 
script: phpunit